services:
    proxy:
        container_name: mc-reverse-proxy
        build:
            context: .
            dockerfile: docker/dockerfile.prod
        restart: unless-stopped
        ports:
            - 8080:8080
            - 8088:8088
            - 25565:25565
        networks:
            - mc-network

networks:
    mc-network:
        driver: bridge